### ISSUE TITLE
Feature Request - Total Counts

### ISSUE THREAD

**Issue by gfranko** [npm/download-counts#1]
I appreciate the new API and just wanted to request that the total download count (for the entire life of an NPM module) be available.  Thanks!

**Comment by erossignon** [comment]
:+1:

**Comment by mpalyart** [comment]
+1, @seldo is the batch job to count totals almost ready?

**Comment by brandonhorst** [comment]
Update on this? all-time downloads would be very useful.

**Comment by seldo** [comment]
This endpoint is now never going to happen. If you'd like all-time totals, you can use a call like 

http://api.npmjs.org/downloads/point/last-year/express 

to get the total for the last 365 days. If your package is older than that, use ranges like 

http://api.npmjs.org/downloads/point/2015-01-01:2015-12-31
http://api.npmjs.org/downloads/point/2016-01-01:2016-12-31

To get totals for each year and add them up (there is currently no data online prior to 2015).
