### ISSUE TITLE
download counts for all packages, per package

### ISSUE THREAD

**Issue by spion** [npm/download-counts#10]
Hi,

I would like to fix [npmsearch](https://github.com/spion/npmsearch), an old module of mine which uses a combination of factors to give nice search results for npm. 

To do this with the current API I would need to send 100K requests to fetch weekly download counts for each package. Thats probably a bad idea, right? But it probably wouldn't be too bad to do one request and receive a list with 100K download counters. 

Would you be open to having another API endpoint for this?

**Comment by seldo** [comment]
The bulk endpoint addresses this use-case:

https://github.com/npm/download-counts#bulk-queries
