### ISSUE TITLE
Are the stats aggregated case insensitively?

### ISSUE THREAD

**Issue by seangarner** [npm/download-counts#20]
Looks like some package stats are incorrectly reported.  Background in npm/newww#707.

Not fully groked the npm architecture, but it looks like it might be caused by line 103 of https://github.com/npm/download-counts/blob/master/scripts/backfill.js

**Comment by mmalecki** [comment]
Thanks for reporting Sean, they indeed are. We already have an issue for that in #13, so I'm going to close this as a duplicate.
