### ISSUE TITLE
Count unique downloads

### ISSUE THREAD

**Issue by fckt** [npm/download-counts#24]
Is npm api capable to provide count of unique downloads?

**Comment by seldo** [comment]
How do you define a "unique" download? A single human? What about build systems? What if the same package is included at two different versions by the same person? What if that person has two separate projects on the same machine using the same package? What if the same project exists on three separate developers' machines? What if it's on their laptop and their desktop?

It's not impossible to come up with reasonable answers to these questions, but a lot of them would involve either requiring everybody to be logged-in to npm to install even public packages, or creating unique tracking IDs per npm installation and sending them with every request, which would be either friction-ful or potentially creepy, so we've avoided it thus far. We also have a limited team size so solving other problems than making download counts more accurate nearly always seems more important.

**Comment by AlexeyFrolov** [comment]
First of all thanks for detailed answer and your time. My concrete need is to figure out the "geo" of my downloads. I think it could be useful to have **ip** and **datetime** of downloads. Having this data API user could make useful considerations, even use heuristics and ML to detect anomalies. If I had this information I (or anybody else) would made such service, with would be useful to **npm** service itself (for DDOS protection for example).

**Comment by seldo** [comment]
I think disclosing the IP of people downloading all packages would constitute a privacy issue.

**Comment by AlexeyFrolov** [comment]
Make sense.. Nevertheless I think It could be useful to have at least some limited, general and depersonalized statistics about package downloads..
