### ISSUE TITLE
Not handling outOfRange flag for range/ endpoint

### ISSUE THREAD

**Issue by mrjoelkemp** [npm/download-counts#25]
It's currently possible to retrieve data for a range much wider than a month. 
1. This should likely be patched if the max range should still be enforced
2. If you're okay with allowing a wider range, there is an issue with an incomplete json response for the payload from the [following request](https://api.npmjs.org/downloads/range/2015-10-28:2015-11-28/hy,me,t1,gh,hf,ho,ud,jo,kj,kr,ks,lr,625,eda,via,enb,enf,bay,exp,ezl,feb,fly,fop,ftx,gak,bus,gco,yun,spm,spa,sir,ghu,gik,sey,gsp,cca,hfb,con,cpx,hyk,ish,itc,ava,rws,cst,js4,jvc,rnp,rmc,xde,kob,d3r,dfp,ldt,ll1,zow,vvc,vsd,nwb,mkr,msx,ngx,seeq,nesh,nbob,nask,nade,npmr,mops,mood,moco,mobo,nrpm,page,mdbp,maku,lumo,pink,pm25,pmap,live,prok,raja,rawt,koto,reqo,rill,kent,kake,rovr,jsxx,jscs,rump,rune,jedi,anpg,avas,ryuu,anny,inxs,injt,axes,inin,sane,sara,hoxy,hola,scaf,sear,ncmb,helm,hear,hazy,sews,gpai,amvn,shan,sqin,sway,tarp,fury,tier,fora,tipm,fnet,tipp,trek,adit,trip,es6y,urly,utea,elle,eint,acre,duce,drug,dosh,doob,diet,wall,deku,wapp,cync,xto6,cqrs,xulf,yaas,cmdr,clif,yobo,zapp,bser,bplt,bmap,beff,loxe,keanu,kanjo,swagc,supra,jtdev,replc,jsxcs,jsdox,jscs2,relex,rekoa,josan,jodel,reiny,regio,javie,jarmo,jaina,jager,stilr,ive-b,ranza,start,prova,xpres,popup,tubbs,ttool,imgop,slock,parse,hulix,xmock,optic,babel,omnom,hihat,omlet,oa.js,shims,addjs,adhoq,noide,gravy,noflo,gitgc,nlint,ya.js,trine,angie,servi,wpcom,tokyo,frish,muder,scipm,tnode,moped,flint,fecmd,armet,feast,faxdb,ezmlm,tisry,moldy,array,es6jq,ereqt,arrow,vdiff,saito,sagui,mkapp,duplo,messg,media,valya,doors,mdcat,dlvid,zpack,markn,thmaa,dabus,madge,rx-ui,cyber,cwine,taula,runjs,uskin,tanok,compy,rtool,zenjs,cinco,choko,choir,routr,carry,rosso,swipe,koa_r,bmson,udder,blogo,blogh,bka14,besix,kinto,rinco,bardo,mekano,domify,zerver,zerojs,kopeer,packup,kr-cli,outlet,kroute,yarnjs,koa-rr,quinnc,lacona,koa-66,knektr,wt-cli,radium,kabuto,wikijs,raichu,jsx-ui,webbox,liftie,js-xdr,vueify,vudash,js-sql,oneref,virtex,jproxy,jestas,varsha,valour,rctapp,vailer,jammin,avalon,invite,pagerz,ohflux,loggle,logify,imlazy,unglob,ui-kit,bamboo,hotbox,nugget,lux.js,hipley,beygir,panels,protoo,troupe,trolly,adjust,tricko,hariko,nt-bus,hal-rc,guvnor,parsec,majora,parsly,nouder,marmot,reactg,noders,prever,to-amd,pavios,reactr,bungle,reactx,gobble,pellet,busola,butane,byways,medium,cakejs,ajaxjs,canals,cassis,catbee,cation).

The incomplete response is likely a non-issue once the range is capped though.

**Comment by seldo** [comment]
Ranges and size of bulk queries are now correctly caped.
