### ISSUE TITLE
Is it possible to get the daily downloads to include the versions downloaded?

### ISSUE THREAD

**Issue by mrjoelkemp** [npm/download-counts#26]
I'd love to get some data on the version of a package being downloaded. Would it be possible to introduce additive data for the daily download endpoint to include a breakdown of versions?

Something like:

```
{
  'foobar': {
    downloads: [
      {
         day: '',
         downloads: 100,
         versions: {
           '1.0.1': 10,
           '1.1.0': 80,
           ...
         }
      }
    ]
  }
}
```

Apologies if this is not the right place for the data request. Happy to recreate the issue elsewhere.

**Comment by JakeChampion** [comment]
Duplicate of https://github.com/npm/download-counts/issues/6 ?

**Comment by mrjoelkemp** [comment]
Whoops!
