### ISSUE TITLE
rate limit

### ISSUE THREAD

**Issue by Brakkar** [npm/download-counts#28]
Hello,
what is the rate limit for pulling data out of this great api ?

**Comment by bcoe** [comment]
@Brakkar we enforce a default rate limit of  `~100` requests a minute on most of our services. I recommend using a library like https://github.com/caolan/async to throttle your requests appropriately. There are not currently many restrictions beyond this. Are you bumping into an issue?

**Comment by Brakkar** [comment]
@bcoe ok. Currently my backend is not nodejs, so I can't use async. But I cache all the GET queries made to the API to get a package downloads count for 12 hours min.

**Comment by Brakkar** [comment]
And here is the result: www.jsdow.com . Hope you like it. Thanks for the great API.

**Comment by seldo** [comment]
This is really great work!

One suggestion: the "percentage" growth charts of a package's downloads relative to itself are interesting, but there is a different metric I track: percentage of total downloads. The whole registry is growing all the time, so everybody's lines always go up. If instead you track a package's downloads as a percentage of full-registry downloads, you can see whether a package is getting more or less popular without the inflationary effect of overall community growth.

**Comment by seldo** [comment]
Oh, and a smaller thing -- you have a framework comparison chart that compares `ember` when their package is really `ember-cli`.

**Comment by Brakkar** [comment]
Hello,
thanks for the suggestions: I modified the chart to use ember-cli .
I see what you mean about the percentage growth calculation, that would be interesting also.
The current percentage setting is indeed useful only for package comparisons, to compare growth rate from a common starting point in the past.

**Comment by Brakkar** [comment]
Hello,
some people ask for scoped packages stats like @turf/distance but I don't see stats for scoped packages. You don't calculate them right ?

**Comment by bcoe** [comment]
@Brakkar unfortunately, the historical approach we use to tracking download counts doesn't support scopes -- this is something we've certainly talked about adding in the future.

You can track the issue here:

https://github.com/npm/registry/issues/59

Is it alright if we close this ticket? you have enough information to work from regarding rate-limits?

**Comment by Brakkar** [comment]
@bcoe ok thank you. Yes you can close this thread, if ever I need info I'll contact you directly.
