### ISSUE TITLE
Scoped packages return 404

### ISSUE THREAD

**Issue by JustinBeckwith** [npm/download-counts#29]
We're trying to get download counts for a few of our packages in the @google npm scope.  I'm trying to hit the API endpoint with this url:
https://api.npmjs.org/downloads/point/last-week/@google/cloud-trace

But... I'm getting a 404 back.  Am I using this thing right?  Thanks!

**Comment by JustinBeckwith** [comment]
FYI @ofrobots

**Comment by seldo** [comment]
Unfortunately the API doesn't support scoped packages because it is really old; we intend to fix that: https://github.com/npm/download-counts/issues/23
