### ISSUE TITLE
dont count 404s as downloads on non-existent modules

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/download-counts#30]
from https://github.com/npm/www/issues/142

<hr/>

https://www.npmjs.com/package/sever

i created this module b/c apparently someone wrote `sever` instead of `seRver` in some script, but it was 404 all that time, and now it came with statusCode:200 and npm counted all those 404s as downloads?..

![screen shot 2017-03-19 at 16 10 59](https://cloud.githubusercontent.com/assets/23745012/24083201/5d0091d4-0cd3-11e7-90b2-954f7b93152b.png)

**Comment by seldo** [comment]
This is not counting 404s. Sever has a tarball for 0.0.2 and it is getting downloaded:

https://registry.npmjs.org/sever

**Comment by noformnocontent** [comment]
i repeat, this a package made _this_ week.

it had 38.834 downloads _the moment_ it was uploaded.
