### ISSUE TITLE
Providing a invalid date gives a 502 Bad Gateway response

### ISSUE THREAD

**Issue by mesaugat** [npm/download-counts#33]
Supposedly, we provide an invalid date for a point or date range. It responds with a 502 response when it actually should be a 400 (Bad Request).

These requests respond with a **502**:
https://api.npmjs.org/downloads/point/2014-02-35
http://api.npmjs.org/downloads/range/2017-01-45:2018-01-01/uuid

However, this request does throw an `invalid date` error with a **400** HTTP status code.
https://api.npmjs.org/downloads/point/2014-02-035

**Comment by bcoe** [comment]
@mesaugat we should now be throwing an appropriate error, mind confirming?

**Comment by mesaugat** [comment]
Works 👍
