### ISSUE TITLE
How to get npm-stats for a closed network/intranet ?

### ISSUE THREAD

**Issue by niteshvudutha** [npm/download-counts#39]
Im not sure whether download-counts works for public repositories alone.
Ours is a closed network.
So, we have our github integrated into client domain as github.client_name.net.
For security reasons, Im not mentioning client name.

Can you tell me what is the approach for getting download-counts in this scenario?

**Comment by seldo** [comment]
We only count downloads from the public registry. If you don't use the public registry, we don't count your downloads.

By default, npm downloads from the public registry. It would only download from a Github repository if you explicitly added git dependencies, which is uncommon.
