### ISSUE TITLE
Why are all weekly download counts most recently zero?

### ISSUE THREAD

**Issue by iONinja** [npm/download-counts#43]
I'm not sure if this is the best place to be asking this. If not, please let me know where to direct my query.

It seems that the weekly download count for every single package has dropped to zero, including the most popular ones. Take Express:

![image](https://user-images.githubusercontent.com/20980384/41015840-6aa87e72-698f-11e8-8fad-f1af301930c4.png)

Surely this is a bug? Any ideas what's going on?

**Comment by aearly** [comment]
https://status.npmjs.org/incidents/b4ktc38pypd1

**Comment by iONinja** [comment]
Ah ha, thanks.
