### ISSUE TITLE
'all-time' download search doesn't work

### ISSUE THREAD

**Issue by Ruturaj4** [npm/download-counts#46]
For eg. I am not able to search -
https://api.npmjs.org/downloads/range/all-time/npm

Am I doing something wrong?

**Comment by arechsteiner** [comment]
You can work with this:

https://api.npmjs.org/downloads/range/2010-01-01:3000-01-01/spur-template

**Comment by Ruturaj4** [comment]
Thanks for info @arechstei. I figured it out though. I set the date as something like 01/01/2014. There is a limit on multi-package query, but I calculated it yearly and then added the results for 5 years (2014 to 2019).
